export { default as Features } from './Features';
export { default as Benefits } from './Benefits';
export { default as About } from './About';
export { default as Advantages } from './Advantages';
export { default as Steps } from './Steps';
export { default as Contact } from './Contact';
export { default as Hero } from './Hero';
export { default as Reviews } from './Reviews';
export { default as Partners } from './Partners';
